CREATE TABLE tokenstakings(
    pk_token_staking_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_staker_account_id bigint REFERENCES accounts(pk_account_id),
    fk_transaction_id bigint references transactions(pk_transaction_id),
    fio_suf_amount bigint
);
