/*
a relic trace is a fio contract action which is called as a result of a relic transaction.
*/
CREATE TABLE traces( 
    pk_trace_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_transaction_id bigint references transactions(pk_transaction_id),
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_action_account_id bigint REFERENCES accounts(pk_account_id), --the authorization used calling this trace action
    fk_receiver_account_id bigint REFERENCES accounts(pk_account_id),
    action_ordinal int,
    action_name varchar(12),
    request_data text);