/*
This table holds FIO account info used by relic.
*/
CREATE TABLE accountsaudit (
   pk_accounts_audit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   fk_account_id bigint references accounts(pk_account_id),
   fk_block_number bigint REFERENCES blocks(pk_block_number),
   account_name varchar(12),
   public_key varchar(53),
   block_timestamp timestamp,
   table_operation varchar(20) NOT NULL CHECK(table_operation IN ('update')),
   table_timestamp timestamp
);
