CREATE TABLE tokentransfers(
    pk_token_transfers_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_payer_account_id bigint REFERENCES accounts(pk_account_id),
    fk_payee_account_id bigint REFERENCES accounts(pk_account_id),
    fk_transaction_id bigint references transactions(pk_transaction_id),
    fio_suf_amount bigint,
    token_transfer_type varchar(20) NOT NULL CHECK(token_transfer_type IN ('transfer','transfer_locked','blockchain_fee','tpid_reward','staking_reward','bp_reward','foundation_reward','oracle_fee','unwrap','token_mint','wrap','retire')),
    transfer_memo text,
    block_timestamp timestamp
);