CREATE TABLE accountactivities (
    pk_account_activity_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_account_id bigint REFERENCES accounts(pk_account_id),
    fk_transaction_id bigint references transactions(pk_transaction_id),
    activity_type varchar(20) NOT NULL CHECK(activity_type IN ('sender','receiver'))
);
