/* this table implements a notion of a relic transaction, 
    a fio blockchain endpoint actionmore modes, and associated data.
    */
CREATE TABLE transactions ( 
    pk_transaction_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number), 
    block_timestamp timestamp,
    transaction_id varchar(80), --this is the fio chain transaction id
    fk_action_account_id bigint REFERENCES accounts(pk_account_id), -- the fio contract account
    fk_account_id bigint REFERENCES accounts(pk_account_id), --the calling actor/authorization for the action being called
    action_name varchar(12),
    tpid varchar(64),
    fee integer,
    request_data text,
    response_data text,
    result_status varchar(120));