/*
CREATE TABLE pubaddresses(
    pk_pub_addresses_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_handle_id bigint REFERENCES handles(pk_handleI_id),
    chain_code varchar(12),
    token_code varchar(12),
    pub_address varchar(128)
);
*/

CREATE OR REPLACE FUNCTION inspubaddresses(  
    fkblocknumber bigint,
    fiohandle varchar(64),
    chaincode varchar(12),
    tokencode varchar(12),
    pubaddress varchar(128)
) RETURNS int     
LANGUAGE 'plpgsql'   
COST 100 
VOLATILE AS 
$BODY$  
    declare pkid bigint;
    declare handleid bigint;
    
    BEGIN  
        IF (fkblocknumber< 0) THEN 
            RETURN -1;
        END IF;
        SELECT pk_handle_id from handles 
            WHERE handle = fiohandle INTO handleid ;
          

        INSERT INTO pubaddresses ( 
            pk_pub_addresses_id,
            fk_block_number,
            fk_handle_id,
            chain_code,
            token_code,
            pub_address
        ) VALUES ( 
            DEFAULT,
            fkblocknumber,
            handleid,
            chaincode,
            tokencode,
            pubaddress
        ) RETURNING pk_pub_addresses_id INTO pkid ;
        RETURN pkid;
    END;
$BODY$;