CREATE TABLE fiodatas(
    pk_fio_data_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fio_chain_request_id bigint,
    fk_payer_handle_id bigint REFERENCES handles(pk_handle_id),
    fk_payee_handle_id bigint REFERENCES handles(pk_handle_id),
    binary_content bytea,
    payer_pub_key varchar(53),
    payee_pub_key varchar(53),
    data_status varchar(20) NOT NULL CHECK(data_status IN ('pending','cancelled','sent_to_blockchain')),
    fk_transaction_id bigint references transactions(pk_transaction_id),
    block_timestamp timestamp
);
