/*
This table holds FIO account info used by relic.
*/
CREATE TABLE accounts (
   pk_account_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   fk_block_number bigint REFERENCES blocks(pk_block_number),
   account_name varchar(12) UNIQUE,
   public_key varchar(53),
   fio_balance_suf bigint,
   block_timestamp timestamp
);
