\ir CreateInsBlocks.sql
\ir CreateInsUpdAccounts.sql 
\ir CreateInsTransactions.sql 
\ir CreateInsTraces.sql
\ir CreateInsAccountActivities.sql 
\ir CreateInsDomains.sql 
\ir CreateInsDomainActivities.sql
\ir CreateUpdDomainExp.sql
\ir CreateUpdDomainIsPublic.sql
\ir CreateInsTokenTransfers.sql
\ir CreateInsTokenStakings.sql
\ir CreateUpdDomainOwner.sql
\ir CreateDelNftSignatures.sql
\ir CreateDelPubAddresses.sql
\ir CreateInsHandleActivities.sql
\ir CreateInsHandleActivitiesFIORequest.sql
\ir CreateInsUpdHandles.sql
\ir CreateUpdHandlesRenewBundles.sql                                   
\ir CreateUpdHandlesXferOwner.sql
\ir CreateDelPubAddress.sql
\ir CreateInsUpdPubAddresses.sql
\ir CreateUpdHandlesAddBundles.sql
\ir CreateUpdHandlesRenewBundles.sql
\ir CreateUpdHandlesEncryptKey.sql
\ir CreateUpdHandlesSetEncryptKey.sql
\ir CreateInsUpdNftSignatures.sql
\ir CreateDelNftSignature.sql
\ir CreateUpdHandlesStatus.sql
\ir CreateInsAccountActivitiesHandle.sql
\ir CreateInsFIORequests.sql
\ir CreateUpdFIORequestsStatus.sql
\ir CreateInsFIODatas.sql
\ir CreateUpdDomainBurnt.sql
\ir CreateExistsPubAddress.sql
\ir CreateUpdHandleBurnt.sql
\ir CreateLogHandlesUpdate.sql
\ir CreateOnHandlesUpdate.sql
\ir CreateLogDomainsUpdate.sql
\ir CreateOnDomainsUpdate.sql
\ir CreateLogAccountsUpdate.sql
\ir CreateOnAccountsUpdate.sql
\ir CreateLogFioRequestsUpdate.sql
\ir CreateOnFioRequestsUpdate.sql
\ir CreateLogFioDatasUpdate.sql
\ir CreateOnFioDatasUpdate.sql
\ir CreateLogPubAddressesUpdate.sql
\ir CreateOnPubAddressesUpdate.sql
\ir CreateLogPubAddressesDelete.sql
\ir CreateOnPubAddressesDelete.sql
\ir CreateLogNFTSignaturesUpdate.sql
\ir CreateOnNFTSignaturesUpdate.sql
\ir CreateLogNFTSignaturesDelete.sql
\ir CreateOnNFTSignaturesDelete.sql
\ir CreateRBHandles.sql
\ir CreateRBDomains.sql
\ir CreateRBAccounts.sql
\ir CreateRBFioRequests.sql
\ir CreateRBFioDatas.sql
\ir CreateRBPubAddresses.sql
\ir CreateRBNFTSignatures.sql
\ir CreateRBFork.sql
