CREATE TABLE pubaddresses(
    pk_pub_addresses_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_handle_id bigint REFERENCES handles(pk_handleI_id),
    chain_code varchar(12),
    token_code varchar(12),
    pub_address varchar(128)
);
