CREATE TABLE domainactivities(
    pk_domain_activity_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_domain_id bigint REFERENCES domains(pk_domain_id),
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_transaction_id bigint references transactions(pk_transaction_id),
    expiration_stamp timestamp,
    domain_activity_type varchar(20) NOT NULL CHECK(domain_activity_type IN ('register','renew','transfer','wrap','unwrap','auto_burn')),
    block_tImestamp timestamp
);