/*
CREATE TABLE pubaddresses(
    pk_pub_addresses_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_handle_id bigint REFERENCES handles(pk_handleI_id),
    chain_code varchar(12),
    token_code varchar(12),
    pub_address varchar(128)
);
*/

CREATE OR REPLACE FUNCTION delpubaddresses(  
    fiohandle varchar(64)
) RETURNS int     
LANGUAGE 'plpgsql'   
COST 100 
VOLATILE AS 
$BODY$  
    declare handleid bigint;
    
    BEGIN  
        SELECT pk_handle_id INTO handleid FROM handles
           WHERE handle = fiohandle;
        DELETE FROM pubaddresses WHERE
            fk_handle_id = handleid;
        RETURN 1;
    END;
$BODY$;