\ir CreateBlocks.sql
\ir CreateAccounts.sql 
\ir CreateTransactions.sql 
\ir CreateTraces.sql
\ir CreateAccountActivities.sql 
\ir CreateDomains.sql 
\ir CreateDomainActivities.sql
\ir CreateHandles.sql
\ir CreateHandleActivities.sql
\ir CreatePubAddresses.sql
\ir CreateNFTSignatures.sql
\ir CreateTokenTransfers.sql
\ir CreateTokenStakings.sql
\ir CreateFIORequests.sql
\ir CreateFIODatas.sql
\ir CreateHandlesAudit.sql
\ir CreateDomainsAudit.sql
\ir CreateAccountsAudit.sql
\ir CreateFIORequestsAudit.sql
\ir CreateFIODatasAudit.sql
\ir CreatePubAddressesAudit.sql
\ir CreateNFTSignaturesAudit.sql
\ir CreateRelicIndexes.sql