CREATE TABLE handlesaudit(
    pk_handles_audit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_handle_id bigint REFERENCES handles(pk_handle_id),
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_domain_id bigint REFERENCES domains(pk_domain_id),
    handle varchar(64),
    fk_owner_account_id bigint REFERENCES accounts(pk_account_id),
    encryption_key varchar(64),
    is_encrypt_key_set boolean DEFAULT false,
    bundled_tx_count integer,
    expiration_stamp timestamp,
    handle_status varchar(20) NOT NULL CHECK(handle_status IN ('active','burnt')),
    table_operation varchar(20) NOT NULL CHECK(table_operation IN ('delete','update')),
    table_timestamp timestamp
);