CREATE TABLE fiorequestsaudit(
    pk_fio_requests_audit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_fio_requests_id bigint references fiorequests(pk_fio_requests_id),
    fk_block_number bigint REFERENCES blocks(pk_block_number), --block number for data.
    fk_table_operation_block_number bigint REFERENCES blocks(pk_block_number), --block number when the update/deletion took place
    fio_chain_request_id bigint,
    fk_payer_handle_id bigint REFERENCES handles(pk_handle_id),
    fk_payee_handle_id bigint REFERENCES handles(pk_handle_id),
    binary_content bytea,
    payer_pub_key varchar(53),
    payee_pub_key varchar(53),
    request_status varchar(20) NOT NULL CHECK(request_status IN ('pending','cancelled','rejected','sent_to_blockchain')),
    fk_transaction_id bigint references transactions(pk_transaction_id),
    block_timestamp timestamp,
    table_operation varchar(20) NOT NULL CHECK(table_operation IN ('update')),
    table_timestamp timestamp
);
