CREATE TABLE domainsaudit(
    pk_domains_audit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_domain_id bigint references domains(pk_domain_id),
    fk_block_number bigint REFERENCES blocks(pk_block_number), --block number for data.
    fk_table_operation_block_number bigint REFERENCES blocks(pk_block_number), --block number when the update/deletion took place
    domain_name varchar(62),
    fk_owner_account_id bigint REFERENCES accounts(pk_account_id),
    is_public boolean,
    expiration_timestamp timestamp,
    domain_status varchar(20) NOT NULL CHECK(domain_status IN ('active','burnt')),
    table_operation varchar(20) NOT NULL CHECK(table_operation IN ('update')),
    table_timestamp timestamp
);