\ir CreateBlocks.sql
\ir CreateAccounts.sql 
\ir CreateTransactions.sql 
\ir CreateTraces.sql
\ir CreateAccountActivities.sql 
\ir CreateDomains.sql 
\ir CreateDomainActivities.sql
\ir CreateHandles.sql
\ir CreateHandleActivities.sql
\ir CreatePubaddresses.sql
\ir CreateNFTSignatures.sql
\ir CreateTokenTransfers.sql
\ir CreateTokenStakings.sql
\ir CreateFIORequests.sql
\ir CreateFIODatas.sql