CREATE TABLE domains (
    pk_domain_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    domain_name varchar(62),
    fk_owner_account_id bigint REFERENCES accounts(pk_account_id),
    is_public boolean,
    expiration_timestamp timestamp,
    domain_status varchar(20) NOT NULL CHECK(domain_status IN ('active','burnt'))
);