CREATE TABLE nftsignatures(
    pk_nft_signatures_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    pk_handle_id bigint REFERENCES handles(pk_handleI_id),
    chain_code varchar(12),
    token_id varchar(64),
    nft_url varchar(128),
    nft_hash varchar(64),
    nft_meta_data varchar(128)
);
