CREATE TABLE nftsignaturesaudit(
    pk_nft_signatures_audit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_nft_signatures_id bigint ,--no constraint to provide delete rollbacks
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_handle_id bigint, --no constraint to provide delete rollbacks
    chain_code varchar(12),
    contract_address varchar(128),
    token_id varchar(128),
    nft_url varchar(128),
    nft_hash varchar(64),
    nft_meta_data varchar(128),
    table_operation varchar(20) NOT NULL CHECK(table_operation IN ('delete','update')),
    table_timestamp timestamp
);
