CREATE TABLE pubaddressesaudit(
    pk_pub_addresses_audit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_pub_addresses_id bigint,--no constraint to support delete of records in audit tables
    fk_block_number bigint REFERENCES blocks(pk_block_number),
    fk_handle_id bigint,
    chain_code varchar(12),
    token_code varchar(12),
    pub_address varchar(128),
    table_operation varchar(20) NOT NULL CHECK(table_operation IN ('delete','update')),
    table_timestamp timestamp
);
